name: "Build"

on:
  push:
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-go@v4
      with:
        go-version: '^1.21.5'

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y gcc-multilib gcc-mingw-w64 binutils-mingw-w64 g++-mingw-w64

    - name: Build
      run: make server

    - name: make dist
      run: make dist

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: com.mkarakiapps.mattermost-image-compression-plugin
        path: dist/com.mkarakiapps.mattermost-image-compression-plugin-*.tar.gz
      

